server:
  port: 9999

spring:
  cloud:
    gateway:
      routes:
        - id: incident-route
          uri: lb://INCIDENT-SERVICE
          predicates:
            - Path=/incidents/**
          filters:
            - TokenRelay=
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: incident-service
            client-secret: LkUnzDd15Zp9oSNjRf7Qz9fVPO4gNbEl
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/incident-realm
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/incident-realm