server.port=8888
spring.application.name=config-server

spring.cloud.config.server.git.uri=file:///C:/Users/pc/Desktop/Projet-Genie-Logiciel-Final/config-repo
spring.cloud.config.server.git.default-label=main

