spring.application.name=incident-service
server.port=8081

# 1. Database Configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/incident_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update

# 2. Eureka Discovery
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# 3. Spring AI Configuration (TinyLlama Local)
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=tinyllama